name: PerfImpact
author: AZ
main: fr.az.perfimpact.Main
version: 2.0
description: 'This plug-in allow you to know the systems impact on performance'
commands:
  perfimpact:
    description: Get the systems performances. Type /perfimpact help for more
    usage: /perfimpact <start|stop|capture|help> ...
    aliases: [pf,perfImpact,PerfImpact,Perfimpact]

permissions:
  perfimpact.use:
    default: true
    description: 'If you did not understood it, you really are a fool'

  perfimpact.start:
    default: true
    description: 'Start the impact mesurement'

  perfimpact.stop:
    default: true
    description: 'Stop the impact mesurement'

  perfimpact.help:
    default: true
    description: 'Getting some help, did you already forget the uses ?'

  perfimpact.resume:
    default: true
    description: 'Get the results of our perfects mesurements !'

  perfimpact.*:
    default: true
    description: 'This is the godly permission !!!'
    children:
      perfimpact.use: true
      perfimpact.start: true
      perfimpact.stop: true
      perfimpact.help: true
      perfimpact.resume: true